
project_id = "ijvtkufzaweqzwczpvgr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[auth]
enabled = true

[functions]
[functions.momo-create-order]
verify_jwt = false
[functions.momo-verify-payment]
verify_jwt = false
[functions.momo-check-subscription]
verify_jwt = false
[functions.payos-create-order]
verify_jwt = false
[functions.payos-verify-payment]
verify_jwt = false
[functions.payos-check-subscription]
verify_jwt = false
[functions.payos-webhook]
verify_jwt = false
[functions.zalopay-create-order]
verify_jwt = false
[functions.zalopay-callback]
verify_jwt = false
[functions.zalopay-check-subscription]
verify_jwt = false
[functions.send-email]
verify_jwt = false
[functions.send-appointment-email]
verify_jwt = false
